# Generated by Django 3.1.7 on 2021-03-31 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeetime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='Name',
        ),
    ]
